services:
  app:
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx_proxy_manager_data:/data
      - nginx_proxy_manager_letsencrypt:/etc/letsencrypt

volumes:
  nginx_proxy_manager_data:
    name: nginx_proxy_manager_data
  nginx_proxy_manager_letsencrypt:
    name: nginx_proxy_manager_letsencrypt
